export const PENTAGRAM = {
    EPSILON: 1e-10,
    ANGLE_OFFSET: 270, // Y축 방향으로 돌리기 위해서 270도를 돌려야 함
    FULL_CIRCLE: 360,
    HALF_CIRCLE: 180,
    SIDES: 5,

    VERTEX_ANGLE_THRESHOLD: 5,
    VERTEX_DISTANCE_THRESHOLD: 10,
    VERTEX_TARGET_DISTANCE: 100,

    PENDING_NODE_OFFSET: 20000,
}