/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
    "\n    mutation updateProfile(\n        $nickname: String,\n        $mutableId: String,\n        $description: String,\n    ) {\n        updateusersCollection(\n            set: {\n                nickname: $nickname,\n                mutable_id: $mutableId,\n                description: $description,\n            }\n        ) {\n            records {\n                id,\n                nickname,\n                mutable_id,\n                description,\n            }\n        }\n    }\n": types.UpdateProfileDocument,
    "\n    fragment ArtistsMinimalInfo on artists {\n        id\n        name\n        updated_at\n    }\n": types.ArtistsMinimalInfoFragmentDoc,
    "\n    fragment ArtistOeuvresInfo on artists {\n        oeuvres_artistsCollection(\n            orderBy: {\n                oeuvre_id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n        ) {\n          \tpageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    oeuvres {\n                        ...OeuvresMinimalInfo\n                    }\n                }\n            }\n        }\n    }\n": types.ArtistOeuvresInfoFragmentDoc,
    "\n    fragment ArtistsInfo on artists {\n        ...ArtistsMinimalInfo\n        ...ArtistOeuvresInfo\n        abstract\n        bio\n    }\n": types.ArtistsInfoFragmentDoc,
    "\n    query getArtistInfoById(\n        $id: UUID!\n        $limit: Int,\n        $cursor: Cursor        \n    ) {\n        artistsCollection(\n            first: 1,\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...ArtistsInfo\n                }\n            }\n        }\n    }\n": types.GetArtistInfoByIdDocument,
    "\n    fragment GenresMinimalInfo on genres {\n        id\n        name\n        updated_at\n    }\n": types.GenresMinimalInfoFragmentDoc,
    "\n    fragment GenreOeuvresInfo on genres {\n        oeuvres_genresCollection(\n            orderBy: {\n                oeuvre_id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n        ) {\n          \tpageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    oeuvres {\n                        ...OeuvresMinimalInfo\n                    }\n                }\n            }\n        }\n    }\n": types.GenreOeuvresInfoFragmentDoc,
    "\n    fragment GenresInfo on genres {\n        ...GenresMinimalInfo,\n        ...GenreOeuvresInfo,\n        abstract\n        description\n    }\n": types.GenresInfoFragmentDoc,
    "\n    query getGenreInfoById(\n        $id: UUID!\n        $limit: Int,\n        $cursor: Cursor    \n    ) {\n        genresCollection(\n            first: 1,\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...GenresInfo\n                }\n            }\n        }\n    }\n": types.GetGenreInfoByIdDocument,
    "\n    fragment OeuvresMinimalInfo on oeuvres {\n        id\n        title\n        updated_at\n    }\n": types.OeuvresMinimalInfoFragmentDoc,
    "\n      fragment OeuvrePentagramsInfo on oeuvres {\n        pentagram_nodesCollection(\n            orderBy: {\n                created_at: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n        ) {\n          \tpageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n              \tcursor\n                node {\n                    pentagrams {\n                        ...PentagramsSelectInfo\n                    }\n                }\n            }\n        }\n    }\n": types.OeuvrePentagramsInfoFragmentDoc,
    "\n    fragment OeuvresInfo on oeuvres {\n        ...OeuvresMinimalInfo\n        ...OeuvrePentagramsInfo\n        description\n        oeuvres_artistsCollection {\n            edges {\n                node {\n                    artists {\n                        ...ArtistsMinimalInfo\n                    }\n                }\n            }\n        },\n        oeuvres_genresCollection {\n            edges {\n                node {\n                    genres {\n                        ...GenresMinimalInfo\n                    }\n                }\n            }\n        }\n    }\n": types.OeuvresInfoFragmentDoc,
    "\n    query getOeuvreInfoById(\n        $id: UUID!\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        oeuvresCollection(\n            first: 1,\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...OeuvresInfo\n                }\n            }\n        }\n    }\n": types.GetOeuvreInfoByIdDocument,
    "\n    fragment UpdateRecordInfo on pentagram_revision_update_records {\n        id\n        pentagram_nodes {\n            oeuvres {\n                ...OeuvresMinimalInfo\n            }\n        }\n        pentagram_revisions {\n            created_at\n        }\n        current_angle\n        current_distance\n        previous_angle\n        previous_distance\n    }\n": types.UpdateRecordInfoFragmentDoc,
    "\n    fragment UpsertRecordInfo on pentagram_revision_upsert_records {\n        id\n        pentagram_nodes {\n            oeuvres {\n                ...OeuvresMinimalInfo\n            }\n        }\n        pentagram_revisions {\n            created_at\n        }\n        current_angle\n        current_distance\n    }\n": types.UpsertRecordInfoFragmentDoc,
    "  \n    fragment RemoveRecordInfo on pentagram_revision_remove_records {\n        id\n        pentagram_nodes {\n            oeuvres {\n                ...OeuvresMinimalInfo\n            }\n        }\n        pentagram_revisions {\n            created_at\n        }\n        previous_angle\n        previous_distance\n    }\n": types.RemoveRecordInfoFragmentDoc,
    "\n    fragment RecoverRecordInfo on pentagram_revision_recover_records {\n        id\n        pentagram_nodes {\n            oeuvres {\n                ...OeuvresMinimalInfo\n            }\n        }\n        pentagram_revisions {\n            created_at\n        }\n        current_angle\n        current_distance\n    }\n": types.RecoverRecordInfoFragmentDoc,
    "\n    fragment PentagramNodesInfo on pentagram_nodes {\n        id\n        oeuvres {\n            ...OeuvresMinimalInfo\n        }\n        pentagram_revision_update_recordsCollection {\n            edges {\n                node {\n                    ...UpdateRecordInfo\n                }\n            }\n        }\n        pentagram_revision_upsert_recordsCollection {\n            edges {\n                node {\n                    ...UpsertRecordInfo\n                }\n            }\n        }\n        pentagram_revision_remove_recordsCollection {\n            edges {\n                node {\n                    ...RemoveRecordInfo\n                }\n            }\n        }\n        pentagram_revision_recover_recordsCollection {\n            edges {\n                node {\n                    ...RecoverRecordInfo\n                }\n            }\n        }\n    }\n": types.PentagramNodesInfoFragmentDoc,
    "\n    fragment PentagramsUpdateInfo on pentagrams {\n        id\n        description\n        created_at\n        users {\n            ...MiniProfileInfo\n        }\n        pentagram_nodesCollection {\n            edges {\n                node {\n                    ...PentagramNodesInfo\n                }\n            }\n        }\n    }\n": types.PentagramsUpdateInfoFragmentDoc,
    "\n    fragment PentagramsSelectInfo on pentagrams {\n        id\n        description\n        created_at\n        users {\n            ...MiniProfileInfo\n        }\n        pentagram_nodesCollection {\n            edges {\n                node {\n                    ...PentagramNodesInfo\n                }\n            }\n        }\n        pentagram_revisionsCollection(\n            orderBy: { created_at: DescNullsLast }\n        ) {\n            edges {\n                node {\n                    ...PentagramRevisionsMinimalInfo\n                }\n            }\n        }\n    }\n": types.PentagramsSelectInfoFragmentDoc,
    "\n    fragment PentagramsSelectUserInfo on pentagrams {\n        id\n        users {\n            ...MiniProfileInfo\n        }\n    }\n": types.PentagramsSelectUserInfoFragmentDoc,
    "\n    fragment PentagramRevisionsInfo on pentagram_revisions {\n        id\n        created_at\n        pentagrams {\n            id\n        }\n        pentagram_revision_update_recordsCollection {\n            totalCount\n            edges {\n                node {\n                    ...UpdateRecordInfo\n                }\n            }\n        }\n        pentagram_revision_upsert_recordsCollection {\n            totalCount\n            edges {\n                node {\n                    ...UpsertRecordInfo\n                }\n            }\n        }\n        pentagram_revision_remove_recordsCollection {\n            totalCount\n            edges {\n                node {\n                    ...RemoveRecordInfo\n                }\n            }\n        }\n        pentagram_revision_recover_recordsCollection {\n            totalCount\n            edges {\n                node {\n                    ...RecoverRecordInfo\n                }\n            }\n        }\n    }\n": types.PentagramRevisionsInfoFragmentDoc,
    "\n    fragment PentagramRevisionsMinimalInfo on pentagram_revisions {\n        id\n        created_at\n        pentagrams {\n            id\n        }\n        pentagram_revision_update_recordsCollection {\n            totalCount\n        }\n        pentagram_revision_upsert_recordsCollection {\n            totalCount\n        }\n        pentagram_revision_remove_recordsCollection {\n            totalCount\n        }\n        pentagram_revision_recover_recordsCollection {\n            totalCount\n        }\n    }\n": types.PentagramRevisionsMinimalInfoFragmentDoc,
    "\n    fragment PentagramRevisionFeedInfo on pentagram_revisions {\n        id\n        created_at\n        users {\n            ...MiniProfileInfo\n        }\n        pentagrams {\n            ...PentagramsSelectInfo\n        }\n    }\n": types.PentagramRevisionFeedInfoFragmentDoc,
    "\n    query getPentagramUpdateInfoById($id: UUID!) {\n        pentagramsCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramsUpdateInfo\n                }\n            }\n        }\n    }\n": types.GetPentagramUpdateInfoByIdDocument,
    "\n    query getPentagramSelectInfoById($id: UUID!) {\n        pentagramsCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramsSelectInfo\n                }\n            }\n        }\n    }\n": types.GetPentagramSelectInfoByIdDocument,
    "\n    query getPentagramsSelectUserInfoById($id: UUID!) {\n        pentagramsCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramsSelectUserInfo\n                }\n            }\n        }\n    }\n": types.GetPentagramsSelectUserInfoByIdDocument,
    "\n    query getPentagramNodesInfoById($id: UUID!) {\n        pentagram_nodesCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramNodesInfo\n                }\n            }\n        }\n    }\n": types.GetPentagramNodesInfoByIdDocument,
    "\n    query getPentagramRevisionsInfoById($id: UUID!) {\n        pentagram_revisionsCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramRevisionsInfo\n                }\n            }\n        }\n    }\n": types.GetPentagramRevisionsInfoByIdDocument,
    "\n    fragment MiniProfileInfo on users {\n        mutable_id,\n        nickname,\n        id,\n        updated_at\n    }\n": types.MiniProfileInfoFragmentDoc,
    "\n    fragment ProfilesInfo on users {\n        ...MiniProfileInfo,\n        description,\n        nickname,\n        ...ProfileFollowInfo,\n        ...ProfilePentagramInfo,\n        ...ProfileRevisionInfo\n    }\n": types.ProfilesInfoFragmentDoc,
    "\n    fragment ProfileFollowInfo on users {\n        followingsCollection {\n            edges {\n                node {\n                    following_id {\n                        ...MiniProfileInfo\n                    }\n                }\n            }\n        }\n        followersCollection {\n            edges {\n                node {\n                    follower_id {\n                        ...MiniProfileInfo\n                    }\n                }\n            }\n        }\n    }\n": types.ProfileFollowInfoFragmentDoc,
    "\n    fragment ProfilePentagramInfo on users {\n        pentagramsCollection(\n            orderBy: {\n                created_at: DescNullsLast\n            }\n            first: $pentagramLimit\n            after: $pentagramCursor\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...PentagramsSelectInfo\n                }\n            }\n        }\n    }\n": types.ProfilePentagramInfoFragmentDoc,
    "\n    fragment ProfileRevisionInfo on users {\n        pentagram_revisionsCollection(\n            orderBy: {\n                created_at: DescNullsLast\n            }\n            first: $revisionLimit\n            after: $revisionCursor\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...PentagramRevisionFeedInfo\n                }\n            }\n        }\n    }\n": types.ProfileRevisionInfoFragmentDoc,
    "\n    mutation insertFollowings($followerId:UUID!, $followingId:UUID!) {\n        insertIntofollowingsCollection(\n            objects: {\n                follower_id: $followerId,\n                following_id: $followingId\n            }\n        ) {\n            records{\n                follower_id { id },\n                follower_id { id }\n            }\n        }\n    }\n": types.InsertFollowingsDocument,
    "\n    mutation deleteFollowings($followerId:UUID!, $followingId:UUID!) {\n        deleteFromfollowingsCollection(\n            filter : {\n                following_id: {eq: $followingId },\n                follower_id: {eq: $followerId}\n            }\n        ) {\n            records {\n                follower_id { id },\n                follower_id { id }\n            }\n        }\n    }\n": types.DeleteFollowingsDocument,
    "\n    query getUserByMutableId(\n        $mutableId: String!\n        $pentagramLimit: Int,\n        $pentagramCursor: Cursor\n        $revisionLimit: Int,\n        $revisionCursor: Cursor\n    ) {\n        usersCollection  (\n            first: 1\n            filter: { mutable_id: { eq: $mutableId } }\n        ) {\n            edges {\n                node {\n                    ...ProfilesInfo\n                }\n            }\n        }\n    }\n": types.GetUserByMutableIdDocument,
    "\n    mutation insertArtists(\n        $title: String,\n        $abstract : String\n        $description: String,\n    ) {\n        insertIntoartistsCollection(\n            objects: {\n                name: $title,\n                abstract: $abstract,\n                bio: $description,\n            }\n        ) {\n            records {\n                id,\n            }\n        }\n    }\n": types.InsertArtistsDocument,
    "\n    mutation insertOeuvres(\n        $title: String,\n        $description: String,\n    ) {\n        insertIntooeuvresCollection(\n            objects: {\n                title: $title,\n                description: $description,\n            }\n        ) {\n            records {\n                id,\n            }\n        }\n    }\n": types.InsertOeuvresDocument,
    "\n    mutation insertGenres(\n        $title: String,\n        $abstract : String\n        $description: String,\n    ) {\n        insertIntogenresCollection(\n            objects: {\n                name: $title,\n                abstract: $abstract,\n                description: $description\n            }\n        ) {\n            records {\n                id,\n            }\n        }\n    }\n": types.InsertGenresDocument,
    "\n    fragment AuthInfo on users {\n        ...MiniProfileInfo,\n        description,\n        nickname,\n        ...ProfileFollowInfo,\n    }\n": types.AuthInfoFragmentDoc,
    "\n    query GetUserById($id: UUID!) {\n        usersCollection(\n            filter: { id: {eq: $id } }\n            first: 1    \n        ) {\n            edges {\n                node {\n                    ...AuthInfo\n                }\n            }\n        }\n    }\n": types.GetUserByIdDocument,
    "\n    fragment FeedInfo on feed {\n        items (\n            orderBy: {\n                created_at: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n              \tcursor\n                node {\n                    ...PentagramRevisionFeedInfo\n                }\n            }\n        }\n    }\n": types.FeedInfoFragmentDoc,
    "\n    fragment FollowRecommendationInfo on feed {\n        recommendation {\n            edges {\n                node {\n                    ...MiniProfileInfo\n                }\n            }\n        }\n    }\n": types.FollowRecommendationInfoFragmentDoc,
    "\n    query GetFeedById(\n        $id: UUID!,\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        feedCollection(filter: { id: {eq: $id } }) {\n            edges {\n                node {\n                    id,\n                    ...FeedInfo\n                }\n            }\n        }\n    }\n": types.GetFeedByIdDocument,
    "\n    query GetFollowRecommendation($id: UUID!) {\n        feedCollection(filter: { id: {eq: $id } }) {\n            edges {\n                node {\n                    ...FollowRecommendationInfo\n                }\n            }\n        }\n    }\n": types.GetFollowRecommendationDocument,
    "\n    query searchOeuvres(\n        $keyword: String!,\n        $limit: Int,\n        $cursor : Cursor\n    ) {\n        oeuvresCollection(\n            orderBy: {\n                id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n            filter: { title: { ilike: $keyword } }\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...OeuvresMinimalInfo\n                }\n            }\n        }\n    }\n": types.SearchOeuvresDocument,
    "\n    query searchUsers(\n        $keyword: String!,\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        usersCollection(\n            orderBy: {\n                mutable_id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n            filter: { mutable_id: { ilike: $keyword } }\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...MiniProfileInfo\n                }\n            }\n        }\n    }\n": types.SearchUsersDocument,
    "\n    query searchArtists(\n        $keyword: String!,\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        artistsCollection(\n            orderBy: {\n                id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n            filter: { name: { ilike: $keyword } }\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...ArtistsMinimalInfo\n                }\n            }\n        }\n    }\n": types.SearchArtistsDocument,
    "\n    query searchGenres(\n        $keyword: String!,\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        genresCollection(\n            orderBy: {\n                id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n            filter: { name: { ilike: $keyword } }\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...GenresMinimalInfo\n                }\n            }\n        }\n    }\n": types.SearchGenresDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation updateProfile(\n        $nickname: String,\n        $mutableId: String,\n        $description: String,\n    ) {\n        updateusersCollection(\n            set: {\n                nickname: $nickname,\n                mutable_id: $mutableId,\n                description: $description,\n            }\n        ) {\n            records {\n                id,\n                nickname,\n                mutable_id,\n                description,\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation updateProfile(\n        $nickname: String,\n        $mutableId: String,\n        $description: String,\n    ) {\n        updateusersCollection(\n            set: {\n                nickname: $nickname,\n                mutable_id: $mutableId,\n                description: $description,\n            }\n        ) {\n            records {\n                id,\n                nickname,\n                mutable_id,\n                description,\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment ArtistsMinimalInfo on artists {\n        id\n        name\n        updated_at\n    }\n"): (typeof documents)["\n    fragment ArtistsMinimalInfo on artists {\n        id\n        name\n        updated_at\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment ArtistOeuvresInfo on artists {\n        oeuvres_artistsCollection(\n            orderBy: {\n                oeuvre_id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n        ) {\n          \tpageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    oeuvres {\n                        ...OeuvresMinimalInfo\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment ArtistOeuvresInfo on artists {\n        oeuvres_artistsCollection(\n            orderBy: {\n                oeuvre_id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n        ) {\n          \tpageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    oeuvres {\n                        ...OeuvresMinimalInfo\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment ArtistsInfo on artists {\n        ...ArtistsMinimalInfo\n        ...ArtistOeuvresInfo\n        abstract\n        bio\n    }\n"): (typeof documents)["\n    fragment ArtistsInfo on artists {\n        ...ArtistsMinimalInfo\n        ...ArtistOeuvresInfo\n        abstract\n        bio\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query getArtistInfoById(\n        $id: UUID!\n        $limit: Int,\n        $cursor: Cursor        \n    ) {\n        artistsCollection(\n            first: 1,\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...ArtistsInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query getArtistInfoById(\n        $id: UUID!\n        $limit: Int,\n        $cursor: Cursor        \n    ) {\n        artistsCollection(\n            first: 1,\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...ArtistsInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment GenresMinimalInfo on genres {\n        id\n        name\n        updated_at\n    }\n"): (typeof documents)["\n    fragment GenresMinimalInfo on genres {\n        id\n        name\n        updated_at\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment GenreOeuvresInfo on genres {\n        oeuvres_genresCollection(\n            orderBy: {\n                oeuvre_id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n        ) {\n          \tpageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    oeuvres {\n                        ...OeuvresMinimalInfo\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment GenreOeuvresInfo on genres {\n        oeuvres_genresCollection(\n            orderBy: {\n                oeuvre_id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n        ) {\n          \tpageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    oeuvres {\n                        ...OeuvresMinimalInfo\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment GenresInfo on genres {\n        ...GenresMinimalInfo,\n        ...GenreOeuvresInfo,\n        abstract\n        description\n    }\n"): (typeof documents)["\n    fragment GenresInfo on genres {\n        ...GenresMinimalInfo,\n        ...GenreOeuvresInfo,\n        abstract\n        description\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query getGenreInfoById(\n        $id: UUID!\n        $limit: Int,\n        $cursor: Cursor    \n    ) {\n        genresCollection(\n            first: 1,\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...GenresInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query getGenreInfoById(\n        $id: UUID!\n        $limit: Int,\n        $cursor: Cursor    \n    ) {\n        genresCollection(\n            first: 1,\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...GenresInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment OeuvresMinimalInfo on oeuvres {\n        id\n        title\n        updated_at\n    }\n"): (typeof documents)["\n    fragment OeuvresMinimalInfo on oeuvres {\n        id\n        title\n        updated_at\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n      fragment OeuvrePentagramsInfo on oeuvres {\n        pentagram_nodesCollection(\n            orderBy: {\n                created_at: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n        ) {\n          \tpageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n              \tcursor\n                node {\n                    pentagrams {\n                        ...PentagramsSelectInfo\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n      fragment OeuvrePentagramsInfo on oeuvres {\n        pentagram_nodesCollection(\n            orderBy: {\n                created_at: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n        ) {\n          \tpageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n              \tcursor\n                node {\n                    pentagrams {\n                        ...PentagramsSelectInfo\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment OeuvresInfo on oeuvres {\n        ...OeuvresMinimalInfo\n        ...OeuvrePentagramsInfo\n        description\n        oeuvres_artistsCollection {\n            edges {\n                node {\n                    artists {\n                        ...ArtistsMinimalInfo\n                    }\n                }\n            }\n        },\n        oeuvres_genresCollection {\n            edges {\n                node {\n                    genres {\n                        ...GenresMinimalInfo\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment OeuvresInfo on oeuvres {\n        ...OeuvresMinimalInfo\n        ...OeuvrePentagramsInfo\n        description\n        oeuvres_artistsCollection {\n            edges {\n                node {\n                    artists {\n                        ...ArtistsMinimalInfo\n                    }\n                }\n            }\n        },\n        oeuvres_genresCollection {\n            edges {\n                node {\n                    genres {\n                        ...GenresMinimalInfo\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query getOeuvreInfoById(\n        $id: UUID!\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        oeuvresCollection(\n            first: 1,\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...OeuvresInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query getOeuvreInfoById(\n        $id: UUID!\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        oeuvresCollection(\n            first: 1,\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...OeuvresInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment UpdateRecordInfo on pentagram_revision_update_records {\n        id\n        pentagram_nodes {\n            oeuvres {\n                ...OeuvresMinimalInfo\n            }\n        }\n        pentagram_revisions {\n            created_at\n        }\n        current_angle\n        current_distance\n        previous_angle\n        previous_distance\n    }\n"): (typeof documents)["\n    fragment UpdateRecordInfo on pentagram_revision_update_records {\n        id\n        pentagram_nodes {\n            oeuvres {\n                ...OeuvresMinimalInfo\n            }\n        }\n        pentagram_revisions {\n            created_at\n        }\n        current_angle\n        current_distance\n        previous_angle\n        previous_distance\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment UpsertRecordInfo on pentagram_revision_upsert_records {\n        id\n        pentagram_nodes {\n            oeuvres {\n                ...OeuvresMinimalInfo\n            }\n        }\n        pentagram_revisions {\n            created_at\n        }\n        current_angle\n        current_distance\n    }\n"): (typeof documents)["\n    fragment UpsertRecordInfo on pentagram_revision_upsert_records {\n        id\n        pentagram_nodes {\n            oeuvres {\n                ...OeuvresMinimalInfo\n            }\n        }\n        pentagram_revisions {\n            created_at\n        }\n        current_angle\n        current_distance\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "  \n    fragment RemoveRecordInfo on pentagram_revision_remove_records {\n        id\n        pentagram_nodes {\n            oeuvres {\n                ...OeuvresMinimalInfo\n            }\n        }\n        pentagram_revisions {\n            created_at\n        }\n        previous_angle\n        previous_distance\n    }\n"): (typeof documents)["  \n    fragment RemoveRecordInfo on pentagram_revision_remove_records {\n        id\n        pentagram_nodes {\n            oeuvres {\n                ...OeuvresMinimalInfo\n            }\n        }\n        pentagram_revisions {\n            created_at\n        }\n        previous_angle\n        previous_distance\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment RecoverRecordInfo on pentagram_revision_recover_records {\n        id\n        pentagram_nodes {\n            oeuvres {\n                ...OeuvresMinimalInfo\n            }\n        }\n        pentagram_revisions {\n            created_at\n        }\n        current_angle\n        current_distance\n    }\n"): (typeof documents)["\n    fragment RecoverRecordInfo on pentagram_revision_recover_records {\n        id\n        pentagram_nodes {\n            oeuvres {\n                ...OeuvresMinimalInfo\n            }\n        }\n        pentagram_revisions {\n            created_at\n        }\n        current_angle\n        current_distance\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment PentagramNodesInfo on pentagram_nodes {\n        id\n        oeuvres {\n            ...OeuvresMinimalInfo\n        }\n        pentagram_revision_update_recordsCollection {\n            edges {\n                node {\n                    ...UpdateRecordInfo\n                }\n            }\n        }\n        pentagram_revision_upsert_recordsCollection {\n            edges {\n                node {\n                    ...UpsertRecordInfo\n                }\n            }\n        }\n        pentagram_revision_remove_recordsCollection {\n            edges {\n                node {\n                    ...RemoveRecordInfo\n                }\n            }\n        }\n        pentagram_revision_recover_recordsCollection {\n            edges {\n                node {\n                    ...RecoverRecordInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment PentagramNodesInfo on pentagram_nodes {\n        id\n        oeuvres {\n            ...OeuvresMinimalInfo\n        }\n        pentagram_revision_update_recordsCollection {\n            edges {\n                node {\n                    ...UpdateRecordInfo\n                }\n            }\n        }\n        pentagram_revision_upsert_recordsCollection {\n            edges {\n                node {\n                    ...UpsertRecordInfo\n                }\n            }\n        }\n        pentagram_revision_remove_recordsCollection {\n            edges {\n                node {\n                    ...RemoveRecordInfo\n                }\n            }\n        }\n        pentagram_revision_recover_recordsCollection {\n            edges {\n                node {\n                    ...RecoverRecordInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment PentagramsUpdateInfo on pentagrams {\n        id\n        description\n        created_at\n        users {\n            ...MiniProfileInfo\n        }\n        pentagram_nodesCollection {\n            edges {\n                node {\n                    ...PentagramNodesInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment PentagramsUpdateInfo on pentagrams {\n        id\n        description\n        created_at\n        users {\n            ...MiniProfileInfo\n        }\n        pentagram_nodesCollection {\n            edges {\n                node {\n                    ...PentagramNodesInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment PentagramsSelectInfo on pentagrams {\n        id\n        description\n        created_at\n        users {\n            ...MiniProfileInfo\n        }\n        pentagram_nodesCollection {\n            edges {\n                node {\n                    ...PentagramNodesInfo\n                }\n            }\n        }\n        pentagram_revisionsCollection(\n            orderBy: { created_at: DescNullsLast }\n        ) {\n            edges {\n                node {\n                    ...PentagramRevisionsMinimalInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment PentagramsSelectInfo on pentagrams {\n        id\n        description\n        created_at\n        users {\n            ...MiniProfileInfo\n        }\n        pentagram_nodesCollection {\n            edges {\n                node {\n                    ...PentagramNodesInfo\n                }\n            }\n        }\n        pentagram_revisionsCollection(\n            orderBy: { created_at: DescNullsLast }\n        ) {\n            edges {\n                node {\n                    ...PentagramRevisionsMinimalInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment PentagramsSelectUserInfo on pentagrams {\n        id\n        users {\n            ...MiniProfileInfo\n        }\n    }\n"): (typeof documents)["\n    fragment PentagramsSelectUserInfo on pentagrams {\n        id\n        users {\n            ...MiniProfileInfo\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment PentagramRevisionsInfo on pentagram_revisions {\n        id\n        created_at\n        pentagrams {\n            id\n        }\n        pentagram_revision_update_recordsCollection {\n            totalCount\n            edges {\n                node {\n                    ...UpdateRecordInfo\n                }\n            }\n        }\n        pentagram_revision_upsert_recordsCollection {\n            totalCount\n            edges {\n                node {\n                    ...UpsertRecordInfo\n                }\n            }\n        }\n        pentagram_revision_remove_recordsCollection {\n            totalCount\n            edges {\n                node {\n                    ...RemoveRecordInfo\n                }\n            }\n        }\n        pentagram_revision_recover_recordsCollection {\n            totalCount\n            edges {\n                node {\n                    ...RecoverRecordInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment PentagramRevisionsInfo on pentagram_revisions {\n        id\n        created_at\n        pentagrams {\n            id\n        }\n        pentagram_revision_update_recordsCollection {\n            totalCount\n            edges {\n                node {\n                    ...UpdateRecordInfo\n                }\n            }\n        }\n        pentagram_revision_upsert_recordsCollection {\n            totalCount\n            edges {\n                node {\n                    ...UpsertRecordInfo\n                }\n            }\n        }\n        pentagram_revision_remove_recordsCollection {\n            totalCount\n            edges {\n                node {\n                    ...RemoveRecordInfo\n                }\n            }\n        }\n        pentagram_revision_recover_recordsCollection {\n            totalCount\n            edges {\n                node {\n                    ...RecoverRecordInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment PentagramRevisionsMinimalInfo on pentagram_revisions {\n        id\n        created_at\n        pentagrams {\n            id\n        }\n        pentagram_revision_update_recordsCollection {\n            totalCount\n        }\n        pentagram_revision_upsert_recordsCollection {\n            totalCount\n        }\n        pentagram_revision_remove_recordsCollection {\n            totalCount\n        }\n        pentagram_revision_recover_recordsCollection {\n            totalCount\n        }\n    }\n"): (typeof documents)["\n    fragment PentagramRevisionsMinimalInfo on pentagram_revisions {\n        id\n        created_at\n        pentagrams {\n            id\n        }\n        pentagram_revision_update_recordsCollection {\n            totalCount\n        }\n        pentagram_revision_upsert_recordsCollection {\n            totalCount\n        }\n        pentagram_revision_remove_recordsCollection {\n            totalCount\n        }\n        pentagram_revision_recover_recordsCollection {\n            totalCount\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment PentagramRevisionFeedInfo on pentagram_revisions {\n        id\n        created_at\n        users {\n            ...MiniProfileInfo\n        }\n        pentagrams {\n            ...PentagramsSelectInfo\n        }\n    }\n"): (typeof documents)["\n    fragment PentagramRevisionFeedInfo on pentagram_revisions {\n        id\n        created_at\n        users {\n            ...MiniProfileInfo\n        }\n        pentagrams {\n            ...PentagramsSelectInfo\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query getPentagramUpdateInfoById($id: UUID!) {\n        pentagramsCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramsUpdateInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query getPentagramUpdateInfoById($id: UUID!) {\n        pentagramsCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramsUpdateInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query getPentagramSelectInfoById($id: UUID!) {\n        pentagramsCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramsSelectInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query getPentagramSelectInfoById($id: UUID!) {\n        pentagramsCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramsSelectInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query getPentagramsSelectUserInfoById($id: UUID!) {\n        pentagramsCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramsSelectUserInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query getPentagramsSelectUserInfoById($id: UUID!) {\n        pentagramsCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramsSelectUserInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query getPentagramNodesInfoById($id: UUID!) {\n        pentagram_nodesCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramNodesInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query getPentagramNodesInfoById($id: UUID!) {\n        pentagram_nodesCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramNodesInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query getPentagramRevisionsInfoById($id: UUID!) {\n        pentagram_revisionsCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramRevisionsInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query getPentagramRevisionsInfoById($id: UUID!) {\n        pentagram_revisionsCollection(\n            filter: { id: { eq: $id } }\n        ) {\n            edges {\n                node {\n                    ...PentagramRevisionsInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment MiniProfileInfo on users {\n        mutable_id,\n        nickname,\n        id,\n        updated_at\n    }\n"): (typeof documents)["\n    fragment MiniProfileInfo on users {\n        mutable_id,\n        nickname,\n        id,\n        updated_at\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment ProfilesInfo on users {\n        ...MiniProfileInfo,\n        description,\n        nickname,\n        ...ProfileFollowInfo,\n        ...ProfilePentagramInfo,\n        ...ProfileRevisionInfo\n    }\n"): (typeof documents)["\n    fragment ProfilesInfo on users {\n        ...MiniProfileInfo,\n        description,\n        nickname,\n        ...ProfileFollowInfo,\n        ...ProfilePentagramInfo,\n        ...ProfileRevisionInfo\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment ProfileFollowInfo on users {\n        followingsCollection {\n            edges {\n                node {\n                    following_id {\n                        ...MiniProfileInfo\n                    }\n                }\n            }\n        }\n        followersCollection {\n            edges {\n                node {\n                    follower_id {\n                        ...MiniProfileInfo\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment ProfileFollowInfo on users {\n        followingsCollection {\n            edges {\n                node {\n                    following_id {\n                        ...MiniProfileInfo\n                    }\n                }\n            }\n        }\n        followersCollection {\n            edges {\n                node {\n                    follower_id {\n                        ...MiniProfileInfo\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment ProfilePentagramInfo on users {\n        pentagramsCollection(\n            orderBy: {\n                created_at: DescNullsLast\n            }\n            first: $pentagramLimit\n            after: $pentagramCursor\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...PentagramsSelectInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment ProfilePentagramInfo on users {\n        pentagramsCollection(\n            orderBy: {\n                created_at: DescNullsLast\n            }\n            first: $pentagramLimit\n            after: $pentagramCursor\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...PentagramsSelectInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment ProfileRevisionInfo on users {\n        pentagram_revisionsCollection(\n            orderBy: {\n                created_at: DescNullsLast\n            }\n            first: $revisionLimit\n            after: $revisionCursor\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...PentagramRevisionFeedInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment ProfileRevisionInfo on users {\n        pentagram_revisionsCollection(\n            orderBy: {\n                created_at: DescNullsLast\n            }\n            first: $revisionLimit\n            after: $revisionCursor\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...PentagramRevisionFeedInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation insertFollowings($followerId:UUID!, $followingId:UUID!) {\n        insertIntofollowingsCollection(\n            objects: {\n                follower_id: $followerId,\n                following_id: $followingId\n            }\n        ) {\n            records{\n                follower_id { id },\n                follower_id { id }\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation insertFollowings($followerId:UUID!, $followingId:UUID!) {\n        insertIntofollowingsCollection(\n            objects: {\n                follower_id: $followerId,\n                following_id: $followingId\n            }\n        ) {\n            records{\n                follower_id { id },\n                follower_id { id }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation deleteFollowings($followerId:UUID!, $followingId:UUID!) {\n        deleteFromfollowingsCollection(\n            filter : {\n                following_id: {eq: $followingId },\n                follower_id: {eq: $followerId}\n            }\n        ) {\n            records {\n                follower_id { id },\n                follower_id { id }\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation deleteFollowings($followerId:UUID!, $followingId:UUID!) {\n        deleteFromfollowingsCollection(\n            filter : {\n                following_id: {eq: $followingId },\n                follower_id: {eq: $followerId}\n            }\n        ) {\n            records {\n                follower_id { id },\n                follower_id { id }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query getUserByMutableId(\n        $mutableId: String!\n        $pentagramLimit: Int,\n        $pentagramCursor: Cursor\n        $revisionLimit: Int,\n        $revisionCursor: Cursor\n    ) {\n        usersCollection  (\n            first: 1\n            filter: { mutable_id: { eq: $mutableId } }\n        ) {\n            edges {\n                node {\n                    ...ProfilesInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query getUserByMutableId(\n        $mutableId: String!\n        $pentagramLimit: Int,\n        $pentagramCursor: Cursor\n        $revisionLimit: Int,\n        $revisionCursor: Cursor\n    ) {\n        usersCollection  (\n            first: 1\n            filter: { mutable_id: { eq: $mutableId } }\n        ) {\n            edges {\n                node {\n                    ...ProfilesInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation insertArtists(\n        $title: String,\n        $abstract : String\n        $description: String,\n    ) {\n        insertIntoartistsCollection(\n            objects: {\n                name: $title,\n                abstract: $abstract,\n                bio: $description,\n            }\n        ) {\n            records {\n                id,\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation insertArtists(\n        $title: String,\n        $abstract : String\n        $description: String,\n    ) {\n        insertIntoartistsCollection(\n            objects: {\n                name: $title,\n                abstract: $abstract,\n                bio: $description,\n            }\n        ) {\n            records {\n                id,\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation insertOeuvres(\n        $title: String,\n        $description: String,\n    ) {\n        insertIntooeuvresCollection(\n            objects: {\n                title: $title,\n                description: $description,\n            }\n        ) {\n            records {\n                id,\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation insertOeuvres(\n        $title: String,\n        $description: String,\n    ) {\n        insertIntooeuvresCollection(\n            objects: {\n                title: $title,\n                description: $description,\n            }\n        ) {\n            records {\n                id,\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    mutation insertGenres(\n        $title: String,\n        $abstract : String\n        $description: String,\n    ) {\n        insertIntogenresCollection(\n            objects: {\n                name: $title,\n                abstract: $abstract,\n                description: $description\n            }\n        ) {\n            records {\n                id,\n            }\n        }\n    }\n"): (typeof documents)["\n    mutation insertGenres(\n        $title: String,\n        $abstract : String\n        $description: String,\n    ) {\n        insertIntogenresCollection(\n            objects: {\n                name: $title,\n                abstract: $abstract,\n                description: $description\n            }\n        ) {\n            records {\n                id,\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment AuthInfo on users {\n        ...MiniProfileInfo,\n        description,\n        nickname,\n        ...ProfileFollowInfo,\n    }\n"): (typeof documents)["\n    fragment AuthInfo on users {\n        ...MiniProfileInfo,\n        description,\n        nickname,\n        ...ProfileFollowInfo,\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetUserById($id: UUID!) {\n        usersCollection(\n            filter: { id: {eq: $id } }\n            first: 1    \n        ) {\n            edges {\n                node {\n                    ...AuthInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetUserById($id: UUID!) {\n        usersCollection(\n            filter: { id: {eq: $id } }\n            first: 1    \n        ) {\n            edges {\n                node {\n                    ...AuthInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment FeedInfo on feed {\n        items (\n            orderBy: {\n                created_at: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n              \tcursor\n                node {\n                    ...PentagramRevisionFeedInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment FeedInfo on feed {\n        items (\n            orderBy: {\n                created_at: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n              \tcursor\n                node {\n                    ...PentagramRevisionFeedInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    fragment FollowRecommendationInfo on feed {\n        recommendation {\n            edges {\n                node {\n                    ...MiniProfileInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment FollowRecommendationInfo on feed {\n        recommendation {\n            edges {\n                node {\n                    ...MiniProfileInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetFeedById(\n        $id: UUID!,\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        feedCollection(filter: { id: {eq: $id } }) {\n            edges {\n                node {\n                    id,\n                    ...FeedInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetFeedById(\n        $id: UUID!,\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        feedCollection(filter: { id: {eq: $id } }) {\n            edges {\n                node {\n                    id,\n                    ...FeedInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query GetFollowRecommendation($id: UUID!) {\n        feedCollection(filter: { id: {eq: $id } }) {\n            edges {\n                node {\n                    ...FollowRecommendationInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query GetFollowRecommendation($id: UUID!) {\n        feedCollection(filter: { id: {eq: $id } }) {\n            edges {\n                node {\n                    ...FollowRecommendationInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query searchOeuvres(\n        $keyword: String!,\n        $limit: Int,\n        $cursor : Cursor\n    ) {\n        oeuvresCollection(\n            orderBy: {\n                id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n            filter: { title: { ilike: $keyword } }\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...OeuvresMinimalInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query searchOeuvres(\n        $keyword: String!,\n        $limit: Int,\n        $cursor : Cursor\n    ) {\n        oeuvresCollection(\n            orderBy: {\n                id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n            filter: { title: { ilike: $keyword } }\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...OeuvresMinimalInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query searchUsers(\n        $keyword: String!,\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        usersCollection(\n            orderBy: {\n                mutable_id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n            filter: { mutable_id: { ilike: $keyword } }\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...MiniProfileInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query searchUsers(\n        $keyword: String!,\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        usersCollection(\n            orderBy: {\n                mutable_id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n            filter: { mutable_id: { ilike: $keyword } }\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...MiniProfileInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query searchArtists(\n        $keyword: String!,\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        artistsCollection(\n            orderBy: {\n                id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n            filter: { name: { ilike: $keyword } }\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...ArtistsMinimalInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query searchArtists(\n        $keyword: String!,\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        artistsCollection(\n            orderBy: {\n                id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n            filter: { name: { ilike: $keyword } }\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...ArtistsMinimalInfo\n                }\n            }\n        }\n    }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query searchGenres(\n        $keyword: String!,\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        genresCollection(\n            orderBy: {\n                id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n            filter: { name: { ilike: $keyword } }\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...GenresMinimalInfo\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query searchGenres(\n        $keyword: String!,\n        $limit: Int,\n        $cursor: Cursor\n    ) {\n        genresCollection(\n            orderBy: {\n                id: DescNullsLast\n            }\n            first: $limit\n            after: $cursor\n            filter: { name: { ilike: $keyword } }\n        ) {\n            pageInfo {\n                hasNextPage\n                endCursor\n            }\n            edges {\n                cursor\n                node {\n                    ...GenresMinimalInfo\n                }\n            }\n        }\n    }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;